/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List products */
        get: operations["listProducts"];
        put?: never;
        /** Create a product */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a product */
        get: operations["getProduct"];
        put?: never;
        post?: never;
        /** Delete a product */
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        /** Update a product */
        patch: operations["updateProduct"];
        trace?: never;
    };
    "/api/v1/products/{productId}/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List branches for a product */
        get: operations["listBranches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}/release-lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a release line */
        post: operations["createReleaseLine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branches/{branchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a branch */
        get: operations["getBranch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a branch */
        patch: operations["updateBranch"];
        trace?: never;
    };
    "/api/v1/branches/{branchId}/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get branch current state */
        get: operations["getBranchCurrentState"];
        /** Update branch current state */
        put: operations["updateBranchCurrentState"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branches/{branchId}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a main snapshot */
        post: operations["createMainSnapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branches/{branchId}/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List releases for a branch */
        get: operations["listReleases"];
        put?: never;
        /** Create a release */
        post: operations["createRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{releaseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a release */
        get: operations["getRelease"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branches/{branchId}/current/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get release graph for branch current state */
        get: operations["getBranchCurrentGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{releaseId}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get release graph for a release */
        get: operations["getReleaseGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Product: {
            /** Format: uuid */
            id?: string;
            name?: string;
            displayName?: string;
            description?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateProductInput: {
            name: string;
            displayName?: string;
            description?: string;
        };
        UpdateProductInput: {
            displayName?: string;
            description?: string;
        };
        BranchLine: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            productId?: string;
            /** @enum {string} */
            type?: "MAIN" | "RELEASE";
            name?: string;
            displayName?: string;
            /** Format: uuid */
            sourceBranchLineId?: string;
            /** Format: uuid */
            forkedFromSnapshotId?: string;
            /** @enum {string} */
            status?: "active" | "maintenance" | "security_only" | "end_of_support" | "closed";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            closedAt?: string;
        };
        CreateReleaseLineInput: {
            name: string;
            displayName?: string;
            /** Format: uuid */
            forkedFromSnapshotId?: string;
        };
        UpdateBranchInput: {
            displayName?: string;
            /** @enum {string} */
            status?: "active" | "maintenance" | "security_only" | "end_of_support" | "closed";
        };
        CurrentState: {
            /** Format: uuid */
            branchLineId?: string;
            /** Format: uuid */
            rootDtProjectUuid?: string;
            rootBomSerialNumber?: string;
            rootBomVersion?: number;
            rootBomSha256?: string;
            sourceRevision?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        UpdateCurrentStateInput: {
            /** Format: uuid */
            rootDtProjectUuid?: string;
            rootBomSerialNumber?: string;
            rootBomVersion?: number;
            rootBomSha256?: string;
            sourceRevision?: string;
        };
        Snapshot: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            branchLineId?: string;
            /** @enum {string} */
            snapshotType?: "MAIN_SNAPSHOT" | "RELEASE";
            version?: string;
            /** @enum {string} */
            status?: "draft" | "testing" | "approved" | "released" | "deprecated" | "end_of_support";
            /** Format: uuid */
            rootDtProjectUuid?: string;
            rootBomSerialNumber?: string;
            rootBomVersion?: number;
            rootBomSha256?: string;
            sourceRevision?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            releasedAt?: string;
        };
        CreateSnapshotInput: {
            version: string;
        };
        CreateReleaseInput: {
            version: string;
        };
        ReleaseGraph: {
            rootNodeId?: string;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            metadata?: components["schemas"]["GraphMetadata"];
        };
        GraphNode: {
            id?: string;
            projectUUID?: string;
            projectName?: string;
            projectVersion?: string;
            bomSerialNumber?: string;
            bomVersion?: number;
            /** @enum {string} */
            resolutionStatus?: "resolved" | "missing_project" | "missing_bom" | "missing_bom_ref" | "invalid";
        };
        GraphEdge: {
            sourceNodeId?: string;
            targetNodeId?: string;
            bomRef?: string;
            /** @enum {string} */
            resolutionStatus?: "resolved" | "missing_project" | "missing_bom" | "missing_bom_ref" | "invalid";
        };
        GraphMetadata: {
            totalNodes?: number;
            totalEdges?: number;
            maxDepthReached?: boolean;
            maxNodesReached?: boolean;
            unresolvedLinks?: number;
            cyclesDetected?: number;
        };
        APIError: {
            error?: string;
            message?: string;
            details?: Record<string, never>;
            requestId?: string;
        };
    };
    responses: {
        /** @description Bad Request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description Not Found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description Dependency-Track Unavailable */
        DTUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
    };
    parameters: {
        ProductId: string;
        BranchId: string;
        ReleaseId: string;
        Limit: number;
        Offset: number;
        MaxDepth: number;
        MaxNodes: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
        };
    };
    listProducts: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"][];
                };
            };
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listBranches: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchLine"][];
                };
            };
        };
    };
    createReleaseLine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReleaseLineInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchLine"];
                };
            };
        };
    };
    getBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: components["parameters"]["BranchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchLine"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: components["parameters"]["BranchId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBranchInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchLine"];
                };
            };
        };
    };
    getBranchCurrentState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: components["parameters"]["BranchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentState"];
                };
            };
        };
    };
    updateBranchCurrentState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: components["parameters"]["BranchId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCurrentStateInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentState"];
                };
            };
        };
    };
    createMainSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: components["parameters"]["BranchId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSnapshotInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
        };
    };
    listReleases: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path: {
                branchId: components["parameters"]["BranchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"][];
                };
            };
        };
    };
    createRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: components["parameters"]["BranchId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReleaseInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
        };
    };
    getRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: components["parameters"]["ReleaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getBranchCurrentGraph: {
        parameters: {
            query?: {
                maxDepth?: components["parameters"]["MaxDepth"];
                maxNodes?: components["parameters"]["MaxNodes"];
            };
            header?: never;
            path: {
                branchId: components["parameters"]["BranchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseGraph"];
                };
            };
            502: components["responses"]["DTUnavailable"];
        };
    };
    getReleaseGraph: {
        parameters: {
            query?: {
                maxDepth?: components["parameters"]["MaxDepth"];
                maxNodes?: components["parameters"]["MaxNodes"];
            };
            header?: never;
            path: {
                releaseId: components["parameters"]["ReleaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseGraph"];
                };
            };
            502: components["responses"]["DTUnavailable"];
        };
    };
}
