/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List products */
        get: operations["listProducts"];
        put?: never;
        /** Create a product */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a product */
        get: operations["getProduct"];
        put?: never;
        post?: never;
        /** Delete a product */
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        /** Update a product */
        patch: operations["updateProduct"];
        trace?: never;
    };
    "/api/v1/products/{productId}/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List branches for a product */
        get: operations["listBranches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}/release-lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a release line */
        post: operations["createReleaseLine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branches/{branchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a branch */
        get: operations["getBranch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a branch */
        patch: operations["updateBranch"];
        trace?: never;
    };
    "/api/v1/branches/{branchId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List versions on a branch (ordered by release datetime) */
        get: operations["listVersions"];
        put?: never;
        /**
         * Create (preset) a version
         * @description Presets a git-like version on the branch line. Only `versionString` is
         *     required; DT projects and release metadata are filled in later.
         */
        post: operations["createVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a version (incl. role-tagged projects) */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        /** Delete a version */
        delete: operations["deleteVersion"];
        options?: never;
        head?: never;
        /** Edit any field (soft immutability) */
        patch: operations["updateVersion"];
        trace?: never;
    };
    "/api/v1/versions/{versionId}/projects/root": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set or replace the single ROOT DT project binding */
        put: operations["setVersionRoot"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/versions/{versionId}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a PROFILE or SUB DT project binding */
        post: operations["addVersionProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/versions/{versionId}/projects/{bindingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a DT project binding */
        delete: operations["removeVersionProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/versions/{versionId}/projects/{role}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** BOM-Link SBOM graph for one role-tagged project */
        get: operations["getProjectGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}/lineage-graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version-lineage graph (RC DB only)
         * @description Nodes are versions; edges are parent/fork lineage. Built purely from the
         *     release catalog database — never calls Dependency-Track and cannot 502.
         */
        get: operations["getProductLineage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{productId}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product-scope release timeline (all branches) */
        get: operations["getProductTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/branches/{branchId}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Branch-scope release timeline */
        get: operations["getBranchTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Product: {
            /** Format: uuid */
            id?: string;
            name?: string;
            displayName?: string;
            description?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateProductInput: {
            name: string;
            displayName?: string;
            description?: string;
        };
        UpdateProductInput: {
            displayName?: string;
            description?: string;
        };
        BranchLine: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            productId?: string;
            /** @enum {string} */
            type?: "MAIN" | "RELEASE";
            name?: string;
            displayName?: string;
            /** Format: uuid */
            sourceBranchLineId?: string;
            /** Format: uuid */
            forkedFromVersionId?: string;
            /** @enum {string} */
            status?: "active" | "maintenance" | "security_only" | "end_of_support" | "closed";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            closedAt?: string;
        };
        CreateReleaseLineInput: {
            name: string;
            displayName?: string;
            /**
             * Format: uuid
             * @description A main-branch version to fork the release line from.
             */
            forkedFromVersionId?: string;
        };
        UpdateBranchInput: {
            displayName?: string;
            /** @enum {string} */
            status?: "active" | "maintenance" | "security_only" | "end_of_support" | "closed";
        };
        Version: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            branchLineId?: string;
            versionString?: string;
            /** @enum {string} */
            status?: "incomplete" | "finalized";
            /** Format: uuid */
            parentVersionId?: string;
            /** Format: uuid */
            forkedFromVersionId?: string;
            location?: string;
            customer?: string;
            /** Format: date-time */
            releaseDate?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            projects?: components["schemas"]["VersionDTProject"][];
        };
        VersionDTProject: {
            id?: number;
            /** Format: uuid */
            versionId?: string;
            /** @enum {string} */
            role?: "ROOT" | "PROFILE" | "SUB";
            /** Format: uuid */
            dtProjectUuid?: string;
            bomSerialNumber?: string;
            bomVersion?: number;
            bomSha256?: string;
            sourceRevision?: string;
            label?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateVersionInput: {
            versionString: string;
            /**
             * Format: uuid
             * @description For a release line's first version, the main version it forks from.
             */
            forkedFromVersionId?: string;
        };
        UpdateVersionInput: {
            versionString?: string;
            /** @enum {string} */
            status?: "incomplete" | "finalized";
            location?: string;
            customer?: string;
            /**
             * Format: date-time
             * @description RFC3339 datetime. An empty string clears the release date.
             */
            releaseDate?: string;
        };
        SetProjectInput: {
            /** Format: uuid */
            dtProjectUuid?: string;
            bomSerialNumber?: string;
            bomVersion?: number;
            bomSha256?: string;
            sourceRevision?: string;
            label?: string;
        };
        AddProjectInput: {
            /** @enum {string} */
            role: "PROFILE" | "SUB";
            /** Format: uuid */
            dtProjectUuid?: string;
            bomSerialNumber?: string;
            bomVersion?: number;
            bomSha256?: string;
            sourceRevision?: string;
            label?: string;
        };
        ReleaseGraph: {
            rootNodeId?: string;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            metadata?: components["schemas"]["GraphMetadata"];
        };
        GraphNode: {
            id?: string;
            projectUUID?: string;
            projectName?: string;
            projectVersion?: string;
            bomSerialNumber?: string;
            bomVersion?: number;
            /** @enum {string} */
            resolutionStatus?: "resolved" | "missing_project" | "missing_bom" | "missing_bom_ref" | "invalid";
        };
        GraphEdge: {
            sourceNodeId?: string;
            targetNodeId?: string;
            bomRef?: string;
            /** @enum {string} */
            resolutionStatus?: "resolved" | "missing_project" | "missing_bom" | "missing_bom_ref" | "invalid";
        };
        GraphMetadata: {
            totalNodes?: number;
            totalEdges?: number;
            maxDepthReached?: boolean;
            maxNodesReached?: boolean;
            unresolvedLinks?: number;
            cyclesDetected?: number;
        };
        LineageGraph: {
            /** Format: uuid */
            productId?: string;
            /** @enum {string} */
            axis?: "version" | "releaseDate";
            nodes?: components["schemas"]["LineageNode"][];
            edges?: components["schemas"]["LineageEdge"][];
        };
        LineageNode: {
            /** Format: uuid */
            versionId?: string;
            /** Format: uuid */
            branchLineId?: string;
            branchName?: string;
            /** @enum {string} */
            branchType?: "MAIN" | "RELEASE";
            versionString?: string;
            /** @enum {string} */
            status?: "incomplete" | "finalized";
            /** Format: date-time */
            releaseDate?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        LineageEdge: {
            /** Format: uuid */
            sourceVersionId?: string;
            /** Format: uuid */
            targetVersionId?: string;
            /** @enum {string} */
            kind?: "parent" | "fork";
        };
        Timeline: {
            entries?: components["schemas"]["TimelineEntry"][];
        };
        TimelineEntry: {
            /** Format: uuid */
            versionId?: string;
            /** Format: uuid */
            branchLineId?: string;
            branchName?: string;
            /** @enum {string} */
            branchType?: "MAIN" | "RELEASE";
            versionString?: string;
            /** @enum {string} */
            status?: "incomplete" | "finalized";
            /** Format: date-time */
            releaseDate?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        APIError: {
            error?: string;
            message?: string;
            details?: Record<string, never>;
            requestId?: string;
        };
    };
    responses: {
        /** @description Bad Request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description Not Found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description Dependency-Track Unavailable */
        DTUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
    };
    parameters: {
        ProductId: string;
        BranchId: string;
        VersionId: string;
        Limit: number;
        Offset: number;
        MaxDepth: number;
        MaxNodes: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
        };
    };
    listProducts: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"][];
                };
            };
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listBranches: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchLine"][];
                };
            };
        };
    };
    createReleaseLine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReleaseLineInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchLine"];
                };
            };
        };
    };
    getBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: components["parameters"]["BranchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchLine"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: components["parameters"]["BranchId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBranchInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchLine"];
                };
            };
        };
    };
    listVersions: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path: {
                branchId: components["parameters"]["BranchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"][];
                };
            };
        };
    };
    createVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: components["parameters"]["BranchId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVersionInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVersionInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    setVersionRoot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetProjectInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionDTProject"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    addVersionProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddProjectInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionDTProject"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    removeVersionProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: components["parameters"]["VersionId"];
                bindingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getProjectGraph: {
        parameters: {
            query?: {
                maxDepth?: components["parameters"]["MaxDepth"];
                maxNodes?: components["parameters"]["MaxNodes"];
            };
            header?: never;
            path: {
                versionId: components["parameters"]["VersionId"];
                role: "ROOT" | "PROFILE" | "SUB";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseGraph"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["DTUnavailable"];
        };
    };
    getProductLineage: {
        parameters: {
            query?: {
                axis?: "version" | "releaseDate";
            };
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineageGraph"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getProductTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getBranchTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                branchId: components["parameters"]["BranchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
